=== EvelikoOfficial/AISKAO/AISKAO_PUBLIC_WEBAPP/src/Eservices.InformationObjects.Xml/Schemas/R-1172_NavalEducationalOrganizationsData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema targetNamespace="http://ereg.egov.bg/segment/R-1172" xmlns="http://ereg.egov.bg/segment/R-1172" xmlns:neoc="http://ereg.egov.bg/value/R-1168" xmlns:neon="http://ereg.egov.bg/value/R-1170" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:import namespace="http://ereg.egov.bg/value/R-1168" schemaLocation="R-1168_NavalEducationalOrganizationCode.xsd" />
  <xsd:import namespace="http://ereg.egov.bg/value/R-1170" schemaLocation="R-1170_NavalEducationalOrganizationName.xsd" />
  <xsd:element name="NavalEducationalOrganizationsData" type="NavalEducationalOrganizationsData" />
  <xsd:complexType name="NavalEducationalOrganizationsData">
    <xsd:annotation>
      <xsd:documentation xml:lang="bg">Учебни заведения и центрове, провеждащи обучение и подготовка на морски лица</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="NavalEducationalOrganizations">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="NavalEducationalOrganization" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="NavalEducationalOrganizationCode" type="neoc:NavalEducationalOrganizationCode" />
                  <xsd:element name="NavalEducationalOrganizationName" type="neon:NavalEducationalOrganizationName" />
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="versionDate" type="xsd:date" use="required" />
  </xsd:complexType>
</xsd:schema>

=== EvelikoOfficial/AISKAO/AISKAO_PUBLIC_WEBAPP/src/Eservices.InformationObjects.Xml/DataPackages/NavalEducationalOrganizationsData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2013 sp1 (http://www.altova.com)-->
<NavalEducationalOrganizationsData versionDate="1967-08-13" xsi:schemaLocation="http://ereg.egov.bg/segment/R-1172 R-1172_NavalEducationalOrganizationsData.xsd" xmlns="http://ereg.egov.bg/segment/R-1172" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<NavalEducationalOrganizations>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>1</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Висше военноморско училище "Н. Й. Вапцаров"</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>2</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Технически университет - Варна</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>3</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>ЯНИАПРЕС ЕООД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>4</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Български морски квалификационен център ЕАД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>5</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Варненска морска гимназия "Св. Николай Чудотворец"</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>6</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Професионална гимназия по морско корабоплаване и риболов "Свети Никола", гр. Бургас</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>7</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>3Д ЕООД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>8</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>АДС Морски център ООД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>9</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Учебен Център Марстар</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>10</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Ригел 55 ЕТ</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>11</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>ПРОМАР ООД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>12</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>ЦПО към "Международен колеж" ООД</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
		<NavalEducationalOrganization>
			<NavalEducationalOrganizationCode>13</NavalEducationalOrganizationCode>
			<NavalEducationalOrganizationName>Друго учебно заведение</NavalEducationalOrganizationName>
		</NavalEducationalOrganization>
	</NavalEducationalOrganizations>
</NavalEducationalOrganizationsData>
